name: linux

on:
  [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
        
    - uses: actions/checkout@v2
    
    - name: Install Curl
      run: sudo apt install curl

    - name: Download
      env:
        git_hash: $(git rev-parse --short "$GITHUB_SHA")
        linux_path: './linux'
      run: curl https://github.com/limsanky/linux/archive/${{ $(git rev-parse --short "$GITHUB_SHA") }}.zip -o ./downloaded

    - name: Decompress
      uses: TonyBogdanov/zip@1.0
      env:
        git_hash: $(git rev-parse --short "$GITHUB_SHA")
        linux_path: './linux'
      with:
        args: unzip -qq ./downloaded/linux-${{ $(git rev-parse --short "$GITHUB_SHA") }}.zip -d ./linux
        
    - name: build
      run: ./build-linux.sh ./linux tinyconfig 

