name: linux

on:
  [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Install Curl
      run: sudo apt install curl
      
    - name: Install Git
      run: sudo apt install git
      
    - name: Declare some variables
      id: vars
      shell: bash
      run: |
        echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
        
    - name: Download Full SHA
      run: curl https://github.com/limsanky/linux/archive/$(GITHUB_SHA).zip -o ./
      
    - name: Decompress Full SHA
      uses: TonyBogdanov/zip@1.0
      with:
        args: unzip -qq ./linux-$(GITHUB_SHA).zip -d ./linux

      
    
