name: linux

on:
  [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Install Curl
      run: sudo apt install curl
      
    - name: Install Git
      run: sudo apt install git
      
